dist: trusty
sudo: false
language: ruby
rvm:
- 2.5.1
env:
- JEKYLL_ENV=production
script:
- "./scripts/build.sh"
deploy:
  provider: pages
  local-dir: _site
  skip-cleanup: true
  target-branch: gh-pages
  github-token: "$GITHUB_TOKEN"
  on:
    branch: master
notifications:
  on_success: change
  on_failure: always
  email: false
  slack:
    secure: QSBzDgbhp+5beTtXrczYjPdzlXSdnFJEMHMuRy24hZbB/Eaojna9ZmP/hjdYYShT9ta6MdL7bqmu8Hcm2uP6D9Dx4pffCMb02RVOE5OliEX7VUlKge3YG/qiLgtA839bFDJbRMrnUszIO/PX2/QRHSGj+5kscEcuVsBI+lgY7kFdlRAdSsx2TXC5pXvzuwUhiBxE2rwQSd8EzlqJVOfeebH6oWxtCjgpjUfydALO83q+rJ8t5Pqh06e5af+DMJO7LK9+t32QQQmsiS4UqmicgijzMsMQycDxOZQjWTMCsSspwMGxO2ALL1Qfr36yfKhCX1jJ5kJehtVmXWUn/QF8fTuIHKjE5kLDyjjhZ8pDOYcQdys6aEQk8IeVeBEc4TkqMnYHv6Mxu9cQOKdBUorU0DQuW4BURz+wHpNegXnUq3XBhcMBT7c2o8I8gZEdtNtODG5qaiinAH0jFJrcdDivQd2nfirQUCFCJmYep87X+wlPZYxdiYW2VNgFnPX/nRYfnhpeliMO85CzimyxDoK7QZRmRYQGGVzaK46R/6F79n5MRV8vzJcLvGTfDX1+W3H3AnMEiEh4TliaXN8i84YcdEGbFzWiyoARKeHEB/V16cF5q1vg+afOf29dzytwHWACcceIBrMueInQ4hn3ot3m1lO7zmZ45wpiOodhMwtczno=
