dist: trusty
sudo: false
language: ruby
rvm:
- 2.5.1
env:
- JEKYLL_ENV=production
script:
- "./scripts/build.sh"
deploy:
  provider: pages
  local-dir: _site
  skip-cleanup: true
  target-branch: gh-pages
  github-token: "$GITHUB_TOKEN"
  on:
    branch: master
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: DyLx6WMKZBhoiwjgtU7tU6mJUP2xFZZAFocGixR9uN5G9NYWhFvSmLlPt7sRg30V6Y7g20lfO/m/QvUZpW9nA/gf1hYV3XspfqFFa901WTBzwss6hqQC3vMqCtkNmwBxZ+swuYepA5kLoZaNiIDlCcmY+6E5T7uRTNZPS4hoCWk/VjpWWibVuXT+kHJAog2CDRUZaSWa5Hcu24iDsFIsGZqxsy8wt0aN0iT+UN4qGDoIqlWE4xtztRVzU/bPRiWRdy1wX2Lf3KRKi3ENzo9YMywNk1ifccfdE0IxxFncMyO1hoyWD5H96DmvSwCAkUwwTKM5P5sobQ9GGmQunbQg1TPncU9O1LpyxRG0rcSO/XyYepKHgqrSZBssicCga5k6hhMbRpDhIx/Indx9S0eboKnwUxtMNH2vpiDw/r3lQoGSSF7J6ZiVh2M4sTTqeO/RxirqlBK8vUPemNoJEj62CCqc9jWfv5i+N7o1qmK+uHIjDXYS6UdqPzM5z9Nfov7CPsMZE1ApqXqhffZ7I1u1tldv7RuatmzrJDVhTRFCQ7ortT4iITaurEeXZqJgH9ZKxx9TxMvgvgQ61/cva3KV9ZCL9DbqpSY0gEewWHF42SttQHozyztgyLI1ynB+bq19FKkfPxD+Q66QHkxDqQdnUOIXuyzzjLMAsqopplWA5h0=
