title: HL2
email: contact@hl2.com
description: >-
  HL2 group est une start-up dédiée à l'Internet des Objets industriel, 
  utilisant les nouvelles technologies LPWAN comme Sigfox™ et LoRaWAN™
baseurl: ""
url: "http://hl2.com"
twitter_username: hl2_fr
github_username:  hl2

google:
  tag_manager:
    container_id: GTM-55HF8C3

assets:
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
plugins:
  - bootstrap
  - font-awesome-sass
  - autoprefixer-rails
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-google-tag-manager

collections:
  events:
  pages:
    output: true
    permalink: /:path

# Exclude from processing.
exclude:
  - .gitignore
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock