title: HL2
email: contact@hl2.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hl2.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hl2_fr
github_username:  hl2

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
plugins:
  - bootstrap
  - font-awesome-sass
  - jekyll-assets
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:path

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
