# Site settings
title: HL2 Group
defaultDescription: Ultra fast prototyping of industrial IoT applications
email: contact@hl2.com
address: 2, avenue Galilée 86961 Chasseneuil Futuroscope - FRANCE
url: "" # the base hostname & protocol for your site
production_url : //hl2.com

twitter_username: HL2group
facebook_username: hl2group

# Team names, titles and social links
founders:
- name: Bernard Le Hetet
  pic: bernard-le-hetet.jpg
  position: Associate

- name: Didier Longueville
  pic: didier-longueville.jpg
  position: CTO

- name: Christian Holweck
  pic: christian-holweck.jpg
  position: Investor relations

members:
- name: Florent Agneray
  pic: florent-agneray.jpg
  position: Chairman

- name: Jean-Louis Guillon
  pic: jean-louis-guillon.jpg
  position: Mechatronics engineer

- name: Mickaël Bosch
  pic: mickael-bosch.jpg
  position: Hardware tech lead

- name: Sophie Roubertie
  pic: sophie-roubertie.jpg
  position: Communication

- name: Kevin Pollet
  pic: kevin-pollet.jpg
  position: Software tech lead

- name: Claude Wesquy
  pic: claude-wesquy.jpg
  position: Business development manager

- name: David Cho-lerat
  pic: david-cho-lerat.jpg
  position: Software engineer

- name: Guillaume Seguin
  pic: guillaume-seguin.jpg
  position: Software engineer

- name: Catherine Lagorre
  pic: catherine-lagorre.jpg
  position: Accounting & admin

- name: Anthony Rabine
  pic: anthony-rabine.jpg
  position: Community manager

# Build settings
markdown: kramdown
