# Site settings
title: HL2 Group
defaultDescription: Ultra fast prototyping of industrial IoT applications
email: contact@hl2.com
address: 2, avenue Galilée 86961 Chasseneuil Futuroscope - FRANCE
url: "" # the base hostname & protocol for your site
production_url : //hl2.com

twitter_username: HL2group
facebook_username: HL2-group-653613411447910

# Team names, titles and social links
founders:
- name: Bernard Le Hetet
  pic: bernard-le-hetet.jpg
  position: CEO
  social:
    - title: linkedin
      url: https://fr.linkedin.com/in/bernard-le-hetet-167180113
- name: Didier Longueville
  pic: didier-longueville.jpg
  position: CTO
- name: Christian Holweck
  pic: christian-holweck.jpg
  position: Investor relations

members:
- name: Florent
  pic: florent-agneray.jpg
  position: Project manager

- name: Mickaël
  pic: mickael-bosch.jpg
  position: Firmware engineer

- name: Philippe
  pic: philippe-delussy.jpg
  position: Business development manager

- name: Kevin
  pic: kevin-pollet.jpg
  position: Software engineer

- name: David
  pic: david-cho-lerat.jpg
  position: Software engineer

- name: Guillaume
  pic: guillaume-seguin.jpg
  position: Software engineer

- name: Catherine
  pic: catherine-lagorre.jpg
  position: Accounting & admin

# Build settings
markdown: kramdown
