# Site settings
title: HL2 Group
defaultDescription: Ultra fast prototyping of industrial IoT applications
email: contact@hl2.com
address: 2, avenue Galilée 86961 Chasseneuil Futuroscope - FRANCE
url: "" # the base hostname & protocol for your site
production_url : //hl2.com

twitter_username: HL2group
facebook_username: hl2group

# Build settings
markdown: kramdown
