# Site settings
title: HL2 Group
author: HL2 Group
description: Ultra fast prototyping of industrial IoT applications
email: contact@hl2.com
address:
  line_1: HL2 group
  line_2: Futuropolis 5, Teleport 4
  line_3: Avenue Thomas Edison
  line_4: 86960 Futuroscope Chasseneuil, France
gmap_parameters: ?q=46.669933,0.363042&ll=46.669933,0.363042&z=19&t=h
googleTagManager: GTM-55HF8C3
url: "" # the base hostname & protocol for your site
production_url : //hl2.com

twitter_username: hl2group
facebook_username: hl2group

openGrapType: website
openGrapImg:
  alt: HL2 group logo
  height: 600
  type: image/jpeg
  url: https://static.hl2.com/images/social_networks/hl2.jpg
  width: 600

# Serving
host: 0.0.0.0

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE.md
  - node_modules
  - package-lock.json
  - package.json
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

# Collections
collections:
  events:
